on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta' or 'dev'
      
      # checking dart and flutter packages
      - name: run-checks
        run: |
          dart --version
          flutter --version

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build project
        id: flutter_build
        run: |
          flutter pub get
          flutter build apk --split-per-abi
      
      - name: Prepare release files
        id: prepare_release
        run: |
          tar -czvf release_build_${{ steps.vars.outputs.sha_short }}.zip build/
          
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/apk/release/app-*-release.apk
            release_${{ steps.vars.outputs.sha_short }}.zip
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: Release ${{ steps.vars.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: my-artifact
      #     path: |
      #       build/app/outputs/apk/release/app-release.apk
      #       release_${{ steps.vars.outputs.sha_short }}.zip
      #     upload_url: ${{steps.create-new-release.outputs.upload_url}}
      #     tag_name: ${{ steps.vars.outputs.sha_short }}
      #     release_name: Release ${{ steps.vars.outputs.sha_short }}