on:
  push:
    branches: [ master ]

name: Create Release

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      # Setup Java environment in order to build the Android app
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta' or 'dev'
      
      # Gradle cache for faster builds
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # Build flutter android app
      - name: Build project
        run: |
          flutter pub get
          flutter build apk --split-per-abi
      
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        id: app-release
        with:
          name: app-release
          path: |
            build/app/outputs/apk/release/app-*-release.apk
  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download Artifacts
        uses: actions/download-artifact@master
        id: download
        with:
          name: app-release
          path: artifact

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.download.outputs.download-path }}/*
          tag_name: ${{ steps.vars.outputs.sha_short }}
          name: Release ${{ steps.vars.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
